// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A Genkit flow that returns a default message when no answer is found.
 *
 * - handleNoAnswer - A function that returns a default no answer message.
 * - HandleNoAnswerInput - The input type for the handleNoAnswer function.
 * - HandleNoAnswerOutput - The return type for the handleNoAnswer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const HandleNoAnswerInputSchema = z.object({
  query: z.string().describe('The user query that could not be answered.'),
});
export type HandleNoAnswerInput = z.infer<typeof HandleNoAnswerInputSchema>;

const HandleNoAnswerOutputSchema = z.object({
  answer: z.string().describe('A default message indicating no answer was found.'),
});
export type HandleNoAnswerOutput = z.infer<typeof HandleNoAnswerOutputSchema>;

export async function handleNoAnswer(input: HandleNoAnswerInput): Promise<HandleNoAnswerOutput> {
  return handleNoAnswerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'handleNoAnswerPrompt',
  input: {schema: HandleNoAnswerInputSchema},
  output: {schema: HandleNoAnswerOutputSchema},
  prompt: `I am sorry, I cannot find the answer to your question: {{{query}}}. Please try again with a different question.`,
});

const handleNoAnswerFlow = ai.defineFlow(
  {
    name: 'handleNoAnswerFlow',
    inputSchema: HandleNoAnswerInputSchema,
    outputSchema: HandleNoAnswerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
